### PR TITLE
Created Magneto tracking page.

### PR DESCRIPTION
**Pull request by bobsummerwill**

### CODE REVIEW

**Review by DonaldMcIntyre — COMMENTED** [review]
- Nanopool confirmed
- STEX confirmed

**Comment by bobsummerwill** [comment]
Thanks, @DonaldMcIntyre.
Updating page now.

**Review by DonaldMcIntyre — COMMENTED** [review]
- MEW ready (thru ETC Coop's Ethercluster)
- Hub Mining Pool ready
- 2miners ready

MyCrypto and Exodus acknowledged notification and will come back with a response.

**Review by DonaldMcIntyre — COMMENTED** [review]
- CrazyPool ready

**Comment by bobsummerwill** [comment]
Thanks, Donald.  Updated.

**Review by DonaldMcIntyre — COMMENTED** [review]
- Exodus confirmed they upgraded

**Review by DonaldMcIntyre — COMMENTED** [review]
- Kraken responded they are ready

**Comment by DonaldMcIntyre** [comment]
- Guarda Wallet is ok
- Ledger is ok

**Review by DonaldMcIntyre — COMMENTED** [review]
- Emerald Wallet is ready

**Review by DonaldMcIntyre — COMMENTED** [review]
Solo Pool is ready

**Comment by bobsummerwill** [comment]
Already updated, thanks, Donald.
Now showing 60% readiness.
I would not be surprised if we don't hear from F2Pool and Coinbase but that they are both ready.

**Review by DonaldMcIntyre — COMMENTED** [review]
Bitfinex ready

**Review by DonaldMcIntyre — COMMENTED** [review]
Coinbase Wallet is ready

**Pull request merged**
